packages:
  - modules/*
  - tests/*
  - platform

allowBuilds:
  esbuild: true
  tldjs: false

minimumReleaseAgeExclude:
  - '@flowdular/sdk@0.3.1'
  - flowdular@0.3.1
  - create-flowdular@0.3.1
  - '@flowdular/sdk@0.3.2'
  - flowdular@0.3.2
  - create-flowdular@0.3.2
  - '@flowdular/sdk@0.4.0'
  - flowdular@0.4.0
  - create-flowdular@0.4.0
