DROP POLICY IF EXISTS parties_idempotency_ledger_tenant_policy ON parties_idempotency_ledger;
DROP INDEX IF EXISTS parties_idempotency_ledger_tenant_operation_idx;
DROP TABLE IF EXISTS parties_idempotency_ledger;
