DROP POLICY IF EXISTS expenses_claims_history_tenant_policy ON expenses_claims_history;
DROP INDEX IF EXISTS expenses_claims_history_tenant_record_version_idx;
DROP TABLE IF EXISTS expenses_claims_history;
